package ch.frily.yubot.util;

public enum EnvKey {
    CRED_TOKEN,
    CRED_DB_URL,
    CRED_DB_USERNAME,
    CRED_DB_PASSWORD,

    GUILD_YUSERVER,

    ROLE_OWNER,
    ROLE_SERVERLEITUNG,
    ROLE_DEVLEITUNG,
    ROLE_AWARENESSLEITUNG,
    ROLE_EVENTLEITUNG,
    ROLE_DESIGNLEITUNG,
    ROLE_MODLEITUNG,
    ROLE_ORGA,
    ROLE_MODERATOR,
    ROLE_SUPPORTLEITUNG,
    ROLE_SUPPORT,
    ROLE_AWARENESS,
    ROLE_DEVELOPER,
    ROLE_EVENT,
    ROLE_DESIGN,
    ROLE_ACTIVEMOD,
    ROLE_EVERYONE,
    ROLE_ANTIFASHIST,
    ROLE_YUTEAM,
    ROLE_EROEFFNUNGSPING,

    CHANNEL_DASTEAM,
    CHANNEL_SERVERGESCHLOSSEN,
    CHANNEL_LOBBY,
    CHANNEL_CLOSURELOGS,
    CHANNEL_COMMUNITYEVENTS,
    CHANNEL_TICKETLOGS,
    CHANNEL_MODINTERN,
    CHANNEL_SUPPORT,
    CHANNEL_COUNTING,
    CHANNEL_LIVESTAGE,
    CHANNEL_STELLDICHVOR,
    CHANNEL_FANART,
    CHANNEL_MUSICDISCUSSION,
    CHANNEL_LYRICLAB,
    CHANNEL_QUEERSPACE,
    CHANNEL_FEEDBACK,
    CHANNEL_KONZERTBEGLEITUNG,
    CHANNEL_YUKONZERTFESTIVALS,
    CHANNEL_JOINTOCREATE,
    CHANNEL_STARTHERE,
    CHANNEL_KETTENBRIEF,

    CATEGORY_TICKETS,
    CATEGORY_ANSAGEN,
    CATEGORY_LIVEVENTS,
    CATEGORY_COMMUNITYFLOOR,
    CATEGORY_VOICE,
    CATEGORY_TEAMBEREICH,

    TIMEZONE;

    String get(){
        return EnvResolver.getString(this);
    }
}
// todo evntl sogar funktional? dass die enum elemente vars sind welche den ..env-aufruf automatisch machen und den wert direkt ausgeben?
